Type: AWS::Amplify::Branch
Properties:
  AppId: !GetAtt AmplifyApp.AppId
  BranchName: main
  Stage: PRODUCTION
  EnableAutoBuild: true
  Framework: 'Next.js - SSR'
  EnvironmentVariables:
    - Name: NEXT_PUBLIC_ENV
      Value: prod
