Type: AWS::Amplify::Branch
Properties:
  AppId: !GetAtt AmplifyApp.AppId
  BranchName: main
  Stage: PRODUCTION
  EnableAutoBuild: true
  EnvironmentVariables:
    - Name: REACT_APP_ENVIRONMENT
      Value: prod
