Type: AWS::Amplify::App
Properties:
  Name: admin-app-${opt:stage}
  Repository: https://github.com/wturon/will-turon
  AccessToken: ${env:REPO_ACCESS_TOKEN, ''}
  IAMServiceRole: !GetAtt AmplifyRole.Arn
  EnvironmentVariables:
    - Name: AMPLIFY_MONOREPO_APP_ROOT
      Value: web
    - Name: AMPLIFY_DIFF_DEPLOY
      Value: false
  BuildSpec: |-
    version: 0.1
    frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - "**/*"
      cache:
        paths:
          - node_modules/**/*
    appRoot: web
