name: ci-build-web

on:
  push:
    branches: [feature/**]
  pull_request:
    branches: [feature/**]

  workflow_dispatch:

env:
  NODE_VERSION: "12.x"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: "checkout branch"
        uses: actions/checkout@v2
      - name: Use Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
