name: deployment-web

on:
  pull_request:
      types: [closed]
      branches: 
        - main
      paths:
        - './web/**'
  workflow_dispatch:

env:
  NODE_VERSION: "12.x"
  AZURE_WEBAPP_PACKAGE_PATH: "./web/build"
  AZURE_WEBAPP_NAME: willturon

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout github action"
        uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Use Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: npm install, build, and test
        run: |
          cd web
          npm install
          npm run build --if-present

      - name: React App Settings Variable Substitution
        run: |
          # Find and Replace using SED on Index
          cd web/build
          sed -i 's|%SUBAPIURI%|${{ secrets.API_URI }}|g' index.html

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: logout
        run: |
          az logout
