name: deployment-api

on:
  pull_request:
      types: [closed]
      branches: [main]
      paths:
        - './api'
  workflow_dispatch:

env:
  NODE_VERSION: "12.x"
  AZURE_WEBAPP_PACKAGE_PATH: "./api"
  AZURE_WEBAPP_NAME: willturon-api

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout github action"
        uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Use Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: npm install
        run: |
          cd api
          npm install
          cd ..

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: logout
        run: |
          az logout
