name: deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  NODE_VERSION: "12.x"
  AZURE_WEBAPP_PACKAGE_PATH: "./build"
  AZURE_WEBAPP_NAME: willturon

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout github action"
        uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Use Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: logout
        run: |
          az logout

      # - name: "Deploy to Azure WebApp"
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
